name: WhiteList
author: Bencor29
website: https://benjamin.cornou.dev
version: 1.1.0
main: fr.bencor29.whitelist.WhiteList
commands:
  whitelist:
    description: Commande principale du plugin.
    aliases:
      - wl
      - whitel
      - wlist
    usage: /<command> help
permissions:
  whitelist.admin:
    description: Permet d'utiliser les commandes du plugin.
    default: op